### ISSUE TITLE
python 3.8.2 error

### ISSUE THREAD

**Issue by ghost** [haexhub/huaweiBootloaderHack#1]
```
Traceback (most recent call last):
  File "unlock.py", line 132, in <module>
    main(sys.argv)
  File "unlock.py", line 119, in main
    failedAttempts  = getFailedAttemptsFromFile(failedAttemptsFilename)
  File "unlock.py", line 30, in getFailedAttemptsFromFile
    array = json.load(file)
  File "PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by TO-OTR** [comment]
same questions

**Comment by ghost** [comment]
doesnt matter cuz it wont work on the latest android security patch anyway
