### ISSUE TITLE
Trying to unlock msm8917

### ISSUE THREAD

**Issue by cristianc** [haexhub/huaweiBootloaderHack#12]
Hi, I've tested your script following instructions included in README but I've got some questions in order to get a successful result.
The main question: what is the max number of shots needed to unlock a huawei device? Waiting for a reply, thanks.

P.S. In my case, there is no need to reboot the device after some shots.

**Comment by haexhub** [comment]
Hi.
If you have the latest version, "isLimitAttemptEnabled" is already set to false. 
So no action is required.
The max number of attempts should be ~250.000. 
Please consider, that with EMUI 10+ you'll be not able to unlock the phone anyway.
You've to downgrade to EMUI 9 or lower.
You can also try https://github.com/mashed-potatoes/PotatoNV.

**Comment by cristianc** [comment]
Hi, unlock.py already includes `isLimitAttemptEnabled   = False`. Btw, when shot number was about 200.000 there was no problem at all, that was normal. Then, a few hours later, I've noticed shot number was about 600.000 but oddly speed was much faster than before and cpu usage was crazy, so I pressed Ctrl+c in order to stop the script. If max number is about 250.000, I dont understand why this limit exceeds in my case.  Anyway, EMUI version is `5.1.3`. Downgrade is not possible in this case if the device is not unlocked. I think I can't test PotatoNV in this msm8917 case because that's about Kirin cpus and not Qualcomm Snapdragon 425. Waiting for a reply, thanks.

**Comment by cristianc** [comment]
P.S. From script's output: 
`* shot 676967 with code 21394480677176460 *
* shot 676968 with code 21394510803476270 *
* shot 676969 with code 21394540929776080 *
* shot 676970 with code 21394571056075890 *
* shot 676971 with code 21394601182375700 *
* shot 676972 with code 21394631308675510 *
* shot 676973 with code 21394661434975320 *
* shot 676974 with code 21394691561275130 *
* shot 676975 with code 21394721687574940 *
* shot 676976 with code 21394751813874750 *
* shot 676977 with code 21394781940174560 *
* shot 676978 with code 21394812066474370 *
* shot 676979 with code 21394842192774180 *
* shot 676980 with code 21394872319073990 *
* shot 676981 with code 21394902445373800 *
* shot 676982 with code 21394932571673610 *
* shot 676983 with code 21394962697973420 *
* shot 676984 with code 21394992824273230 *
* shot 676985 with code 21395022950573040 *
* shot 676986 with code 21395053076872850 *
* shot 676987 with code 21395083203172660 *
* shot 676988 with code 21395113329472470 *
* shot 676989 with code 21395143455772280 *
* shot 676990 with code 21395173582072090 *
* shot 676991 with code 21395203708371900 *
* shot 676992 with code 21395233834671710 *
* shot 676993 with code 21395263960971520 *
* shot 676994 with code 21395294087271330 *
* shot 676995 with code 21395324213571140 *
* shot 676996 with code 21395354339870950 *
* shot 676997 with code 21395384466170760 *
* shot 676998 with code 21395414592470570 *
* shot 676999 with code 21395444718770380 *
* shot 677000 with code 21395474845070190 *
^CTraceback (most recent call last):
  File "unlock.py", line 136, in <module>
    main(sys.argv)
  File "unlock.py", line 124, in main
    codeOEM         = tryUnlockBootloader(imei, checksum, failedAttempts)
  File "unlock.py", line 102, in tryUnlockBootloader
    writeFailedAttemptsToFile(failedAttemptsFilename, list(failedAttempts))
  File "unlock.py", line 45, in writeFailedAttemptsToFile
    json.dump(failedAttempts, file)
  File "/usr/lib64/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.6/json/encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib64/python3.6/json/encoder.py", line 301, in _iterencode_list
    if isinstance(value, str):
KeyboardInterrupt`
