### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by swissk** [haexhub/huaweiBootloaderHack#8]
Great little app. Thank you for your time and effort. I hope it will unlock my phone.

**Comment by ShadowSonic** [comment]
Hi,
I have now several times to use this script, but unfortunately I always get an error message.
```
C:\Users\root\Downloads\huaweiBootloaderHack>C:\Users\root\AppData\Local\Programs\Python\Python39\python.exe unlock.py 86726003957554

*****************************************************************************
*         Unlock Huawei Bootloader - Made by Haex inspired by SkyEmie       *
*                                                                           *
*  Please enable USB DEBBUG and OEM UNLOCK if your device does not appear   *
*                                                                           *
*           Be aware of lossing all your data => do backup ;)               *
*****************************************************************************

Traceback (most recent call last):
  File "C:\Users\root\Downloads\huaweiBootloaderHack\unlock.py", line 137, in <module>
    main(sys.argv)
  File "C:\Users\root\Downloads\huaweiBootloaderHack\unlock.py", line 111, in main
    subprocess.run(['adb', 'devices'])
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

I have installed the Android Studio incl. the SDK's, tested Python via the MS Store as well as my own installation, but unfortunately without success. What file can not find the script?
