### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by LuthorDevelopment** [haexhub/huaweiBootloaderHack#9]
Hi,
I have now several times to use this script, but unfortunately I always get an error message.
```
C:\Users\root\Downloads\huaweiBootloaderHack>C:\Users\root\AppData\Local\Programs\Python\Python39\python.exe unlock.py 86726003957554

*****************************************************************************
*         Unlock Huawei Bootloader - Made by Haex inspired by SkyEmie       *
*                                                                           *
*  Please enable USB DEBBUG and OEM UNLOCK if your device does not appear   *
*                                                                           *
*           Be aware of lossing all your data => do backup ;)               *
*****************************************************************************

Traceback (most recent call last):
  File "C:\Users\root\Downloads\huaweiBootloaderHack\unlock.py", line 137, in <module>
    main(sys.argv)
  File "C:\Users\root\Downloads\huaweiBootloaderHack\unlock.py", line 111, in main
    subprocess.run(['adb', 'devices'])
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

I have installed the Android Studio incl. the SDK's, tested Python via the MS Store as well as my own installation, but unfortunately without success. What file can not find the script?

**Comment by haexhub** [comment]
Hi,

it seems, that the program can't find the failedAttempts.json file.
You could create it by your own, or you can pull the latest version of the repo.
